# Site settings
title: 그림 그리는 끌나
email: kkeulna775859@gmail.com
author: 끌나 the potato

keywords: jekyll, jekyll theme, portfolio theme, artist theme
description: 그림 그리는 그저 평범한 감자입니다.
# Only use this if you are serving your site via Github Pages
github:
  url: "https://kkeulna.github.io"

header: images/logo.png



# stats
remote_theme: FredEkstrand/jekyll-theme-slateb


# Build settings
markdown: kramdown
kramdown:
  input: GFM


  
# Plugins
gems:
  - jekyll-feed

feed:
  path: atom.xml
  
# Compress our Css
#sass:
#    style: :compressed

include: ['_pages']

permalink: /blog/:year/:title

collections:
  - galleries

#### SEO Stuff
# Google Analytics
google_universal_analytics: 
google_universal_analytics_cookiedomain: auto

# Facebook Opengraph
facebook_user:
facebook_app_id:                                #enter your App ID
facebook_locale: en_US
facebook_page:                                  #the URL of your Facebook Page
facebook_image: images/author.jpg                      #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

# Twitter Cards
twitter_user: rjseka7758
twitter_card: true
twitter_image: images/author.jpg                       #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.
